export * from './test/test.controller'
export * from './complaint/complaint.controller'
export * from './type-crime/type-crime.controller'
export * from './user/user.controller'
export * from './object/object.controller'